plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/dorischen/WorkBuddy/20260603094738/happy-diary-cloud"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]